version: '3'
services:
  webapp:
    build:
      context: ../../../
      dockerfile: config/docker/dev/Dockerfile-dev
    container_name: aviacommerce-dev
    volumes:
      - ../../../:/avia-backend
    ports:
      - "4000:4000"
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snitch_dev
    ports:
      - "5432:5432"
